<a href="https://colab.research.google.com/github/Dhiviya25/IPL-data-analysis/blob/main/Bangalore_tech_salaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Dhiviya R

Dataset: bangalore_tech_salaries.csv

Objectives: Clean and analyze Bangalore tech salary and build a salary intelligence report

TASK 1

In [ ]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
df = pd.read_csv("bangalore_tech_salaries.csv").copy()

df.head()

,Employee_ID,Role,years_exp,Current_CTC,Previous_CTC,Company,company_TYPE,Skills,Location,Education_Tier,Joining_Year,Work_Mode
0,BLR0065,DS,6,49.4,32.4 LPA,Ola,Unicorn,"JIRA, JavaScript, Spring Boot, Figma, NumPy, A...",HSR Layout,Tier-1,2022,Remote
1,BLR0080,DevOps,0,9.7,NaN,Walmart Labs,MNC,"Tableau, Python, Figma, JavaScript, TensorFlow",Electronic City,2,2024,Remote
2,BLR0166,SDE Backend,6,"3,360,000",24.2 LPA,Postman,Mid-size,"Agile, Excel, GCP, MongoDB, Java, ML",Whitefield,Tier-1,2023,Hybrid
3,BLR0219,SDE Frontend,8,41.4 LPA,30.3,Amazon India,MNC,"PyTorch, Redis, System Design",MG Road,Tier-2,2022,Work from Office
4,BLR0491,Product Lead,5,"3,640,000",30.6 LPA,QuickPay AI,early-stage,"Tableau, Deep Learning, Agile",Whitefield,Tier-2,2023,Onsite

In [ ]:
print("Shape of Dataset")
print(df.shape)

print("\n")

print("Column Names")
print(df.columns)

print("\n")

print("Data Types")
print(df.dtypes)

Shape of Dataset
(1015, 12)


Column Names
Index(['Employee_ID', 'Role ', 'years_exp', 'Current_CTC', 'Previous_CTC',
       'Company', 'company_TYPE', 'Skills', 'Location', 'Education_Tier',
       'Joining_Year', 'Work_Mode'],
      dtype='object')


Data Types
Employee_ID       object
Role              object
years_exp          int64
Current_CTC       object
Previous_CTC      object
Company           object
company_TYPE      object
Skills            object
Location          object
Education_Tier    object
Joining_Year       int64
Work_Mode         object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1015 entries, 0 to 1014
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Employee_ID     1015 non-null   object
 1   Role            1015 non-null   object
 2   years_exp       1015 non-null   int64
 3   Current_CTC     1015 non-null   object
 4   Previous_CTC    815 non-null    object
 5   Company         1015 non-null   object
 6   company_TYPE    1015 non-null   object
 7   Skills          988 non-null    object
 8   Location        995 non-null    object
 9   Education_Tier  1015 non-null   object
 10  Joining_Year    1015 non-null   int64
 11  Work_Mode       1015 non-null   object
dtypes: int64(2), object(10)
memory usage: 95.3+ KB

In [ ]:
df.describe(include='all')

,Employee_ID,Role,years_exp,Current_CTC,Previous_CTC,Company,company_TYPE,Skills,Location,Education_Tier,Joining_Year,Work_Mode
count,1015,1015,1015.000000,1015,815,1015,1015,988,995,1015,1015.000000,1015
unique,1000,42,NaN,702,437,36,11,973,11,12,NaN,6
top,BLR0331,BA,NaN,11.7,15.4,Chargebee,MNC,"JavaScript, Agile, PostgreSQL, Azure, ML, Powe...",Electronic City,2,NaN,Hybrid
freq,2,43,NaN,5,8,44,319,2,106,141,NaN,179
mean,NaN,NaN,3.429557,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022.698522,NaN
std,NaN,NaN,2.558721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.308351,NaN
min,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020.000000,NaN
25%,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022.000000,NaN
50%,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.000000,NaN
75%,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.000000,NaN
max,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.000000,NaN

In [ ]:
print(df.isnull().sum())

Employee_ID         0
Role                0
years_exp           0
Current_CTC         0
Previous_CTC      200
Company             0
company_TYPE        0
Skills             27
Location           20
Education_Tier      0
Joining_Year        0
Work_Mode           0
dtype: int64

In [ ]:
print("Duplicate Rows :",df.duplicated().sum())

Duplicate Rows : 15

In [ ]:
print("="*60)

print("DATASET QUALITY SUMMARY")

print("="*60)

print("Total Rows :",len(df))

print("Total Columns :",len(df.columns))

print("Duplicate Rows :",df.duplicated().sum())

print("\nMissing Values")

print(df.isnull().sum().sort_values(ascending=False))

print("="*60)

============================================================
DATASET QUALITY SUMMARY
============================================================
Total Rows : 1015
Total Columns : 12
Duplicate Rows : 15

Missing Values
Previous_CTC      200
Skills             27
Location           20
Employee_ID         0
Current_CTC         0
years_exp           0
Role                0
Company             0
company_TYPE        0
Education_Tier      0
Joining_Year        0
Work_Mode           0
dtype: int64
============================================================

TASK 2

In [ ]:
df.columns = df.columns.str.lower()

df.columns = df.columns.str.replace(" ","_")

df.columns

Index(['employee_id', 'role_', 'years_exp', 'current_ctc', 'previous_ctc',
       'company', 'company_type', 'skills', 'location', 'education_tier',
       'joining_year', 'work_mode'],
      dtype='object')

In [ ]:
for col in df.columns:
    if df[col].dtype=="object":
        df[col]=df[col].str.strip()

In [ ]:
print(df.columns.tolist())

['employee_id', 'role_', 'years_exp', 'current_ctc', 'previous_ctc', 'company', 'company_type', 'skills', 'location', 'education_tier', 'joining_year', 'work_mode']

In [ ]:
print(df.head())

  employee_id         role_  years_exp current_ctc previous_ctc       company  \
0     BLR0065            DS          6        49.4     32.4 LPA           Ola
1     BLR0080        DevOps          0         9.7          NaN  Walmart Labs
2     BLR0166   SDE Backend          6   3,360,000     24.2 LPA       Postman
3     BLR0219  SDE Frontend          8    41.4 LPA         30.3  Amazon India
4     BLR0491  Product Lead          5   3,640,000     30.6 LPA   QuickPay AI

  company_type                                             skills  \
0      Unicorn  JIRA, JavaScript, Spring Boot, Figma, NumPy, A...
1          MNC     Tableau, Python, Figma, JavaScript, TensorFlow
2     Mid-size               Agile, Excel, GCP, MongoDB, Java, ML
3          MNC                      PyTorch, Redis, System Design
4  early-stage                      Tableau, Deep Learning, Agile

          location education_tier  joining_year         work_mode
0       HSR Layout         Tier-1          2022            Remote
1  Electronic City              2          2024            Remote
2       Whitefield         Tier-1          2023            Hybrid
3          MG Road         Tier-2          2022  Work from Office
4       Whitefield         Tier-2          2023            Onsite

In [ ]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")

In [ ]:
print(df.columns.tolist())

['employee_id', 'role_', 'years_exp', 'current_ctc', 'previous_ctc', 'company', 'company_type', 'skills', 'location', 'education_tier', 'joining_year', 'work_mode']

In [ ]:
df['company_type_clean'] = df['company_type'].str.strip().str.title()

print(df['company_type_clean'].value_counts())

company_type_clean
Mnc            348
Mid-Size       261
Unicorn        207
Early-Stage    199
Name: count, dtype: int64

In [ ]:
df['education_tier_clean'] = df['education_tier'].replace({
    'T1':'Tier 1',
    '1':'Tier 1',
    'Tier-1':'Tier 1',
    'T2':'Tier 2',
    '2':'Tier 2',
    'Tier-2':'Tier 2',
    'T3':'Tier 3',
    '3':'Tier 3',
    'Tier-3':'Tier 3'
})

df['education_tier_clean'] = df['education_tier_clean'].fillna(df['education_tier'])

print(df['education_tier_clean'].value_counts())

education_tier_clean
Tier 2    510
Tier 3    309
Tier 1    196
Name: count, dtype: int64

In [ ]:
def convert_ctc(ctc):

    if pd.isna(ctc):
        return np.nan

    ctc = str(ctc).replace('₹','').replace('LPA','').replace(',','').strip()

    value = float(ctc)

    if value > 1000:
        value = value/100000

    return value

In [ ]:
df['current_ctc_lpa'] = df['current_ctc'].apply(convert_ctc)

df['previous_ctc_lpa'] = df['previous_ctc'].apply(convert_ctc)

df[['current_ctc','current_ctc_lpa']].head()

  current_ctc  current_ctc_lpa
0        49.4             49.4
1         9.7              9.7
2   3,360,000             33.6
3    41.4 LPA             41.4
4   3,640,000             36.4

In [ ]:
df = df.drop_duplicates()

print("Dataset Shape:", df.shape)

Dataset Shape: (1000, 16)

In [ ]:
print(df.dtypes)

employee_id              object
role_                    object
years_exp                 int64
current_ctc              object
previous_ctc             object
company                  object
company_type             object
skills                   object
location                 object
education_tier           object
joining_year              int64
work_mode                object
company_type_clean       object
education_tier_clean     object
current_ctc_lpa         float64
previous_ctc_lpa        float64
dtype: object

In [ ]:
df['role_clean'] = df['role_'].replace({
    'Backend Engineer': 'SDE Backend',
    'Backend Dev': 'SDE Backend',
    'Backend Developer': 'SDE Backend',
    'BE': 'SDE Backend',
    'Frontend Engineer': 'SDE Frontend',
    'Frontend Dev': 'SDE Frontend',
    'Full Stack Developer': 'SDE Full Stack',
    'Full Stack Engineer': 'SDE Full Stack',
    'SDE Full-Stack': 'SDE Full Stack'
})

df['role_clean'] = df['role_clean'].fillna(df['role_'])

/tmp/ipykernel_722/186479227.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['role_clean'] = df['role_'].replace({
/tmp/ipykernel_722/186479227.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['role_clean'] = df['role_clean'].fillna(df['role_'])

TASK 3

In [ ]:
print(df.dtypes)

print("\nRole:")
print(df['role_clean'].value_counts())

print("\nCompany Type:")
print(df['company_type_clean'].value_counts())

print("\nEducation Tier:")
print(df['education_tier_clean'].value_counts())

print("\nCurrent CTC:")
print(df[['current_ctc','current_ctc_lpa']].head())

employee_id              object
role_                    object
years_exp                 int64
current_ctc              object
previous_ctc             object
company                  object
company_type             object
skills                   object
location                 object
education_tier           object
joining_year              int64
work_mode                object
company_type_clean       object
education_tier_clean     object
current_ctc_lpa         float64
previous_ctc_lpa        float64
role_clean               object
dtype: object

Role:
role_clean
SDE Backend                  93
SDE Frontend                 57
BA                           41
Data Scientist               39
SDE Full Stack               38
Business Analyst             35
Site Reliability Engineer    33
Business Systems Analyst     32
ML Engineer                  31
Product Lead                 31
Data Science Engineer        30
PM                           28
Designer                     28
BI Analyst                   28
SRE                          28
DA                           27
Product Manager              27
Sr PM                        26
DS                           25
SDE FS                       24
DevOps Engineer              24
Frontend Developer           24
Data Analyst                 23
Product Designer             23
UI/UX                        23
DevOps                       22
Analytics Engineer           22
SDE-Backend                  21
UI Designer                  20
Infra Engineer               20
FullStack                    20
UX Designer                  19
Fullstack Dev                14
SDE-Frontend                 12
FE                           12
Name: count, dtype: int64

Company Type:
company_type_clean
Mnc            342
Mid-Size       257
Unicorn        207
Early-Stage    194
Name: count, dtype: int64

Education Tier:
education_tier_clean
Tier 2    500
Tier 3    306
Tier 1    194
Name: count, dtype: int64

Current CTC:
  current_ctc  current_ctc_lpa
0        49.4             49.4
1         9.7              9.7
2   3,360,000             33.6
3    41.4 LPA             41.4
4   3,640,000             36.4

TASK 3.1

In [ ]:
role_salary = df.groupby('role_clean')['current_ctc_lpa'].agg(
    Median_CTC='median',
    Mean_CTC='mean',
    Min_CTC='min',
    Max_CTC='max'
).sort_values(by='Median_CTC', ascending=False)

print(role_salary.round(2))

                           Median_CTC  Mean_CTC  Min_CTC  Max_CTC
role_clean
Product Manager                 31.60     34.39     14.2     80.1
Sr PM                           31.50     35.40     10.8     65.5
Product Lead                    31.10     30.78     12.0     55.1
PM                              30.10     36.41     13.8     78.5
ML Engineer                     27.50     30.34     10.0     64.5
Data Science Engineer           25.65     28.36     14.3     75.6
FE                              25.30     24.11     11.5     31.1
SDE FS                          24.60     28.61     11.5     70.9
Fullstack Dev                   24.55     21.82      9.0     33.4
Frontend Developer              24.30     23.60     11.0     39.4
SRE                             24.25     24.28      8.8     49.5
Data Scientist                  23.90     25.75     11.7     73.5
Infra Engineer                  23.45     22.61      9.2     45.5
Site Reliability Engineer       22.20     23.33      9.9     55.0
UI/UX                           22.00     21.57      6.2     44.1
SDE Full Stack                  21.70     26.73     10.7     71.7
Analytics Engineer              21.40     20.91      6.8     37.9
SDE Backend                     21.30     23.11      7.9     55.1
DevOps Engineer                 21.15     25.41      9.8     60.3
SDE Frontend                    21.00     22.26      6.7     84.4
DS                              21.00     26.09     10.9     56.1
Business Systems Analyst        20.90     22.07      6.8     52.2
SDE-Backend                     20.60     24.07      9.3     49.8
BA                              20.50     22.82      7.6     52.7
UI Designer                     19.50     19.92      8.6     44.5
Product Designer                19.00     21.53     10.9     55.7
UX Designer                     18.00     23.27      6.6     63.3
Designer                        17.90     19.20      7.1     43.8
FullStack                       17.60     21.57      8.9     45.3
DevOps                          17.10     20.14      9.7     52.6
Data Analyst                    16.70     17.73      5.6     43.4
BI Analyst                      16.45     16.78      5.2     36.3
Business Analyst                16.40     20.58      6.8     44.9
SDE-Frontend                    16.25     17.13     12.1     27.3
DA                              15.90     16.65      5.9     30.4

TASK 3.2

In [ ]:
backend = df[df['role_clean'] == 'SDE Backend'].copy()

bins = [0, 2, 4, 6, 100]

labels = ['0-1', '2-3', '4-5', '6+']

backend['exp_band'] = pd.cut(
    backend['years_exp'],
    bins=bins,
    labels=labels,
    right=False
)

exp_salary = backend.groupby('exp_band')['current_ctc_lpa'].median()

print(exp_salary.round(2))

exp_band
0-1    11.70
2-3    19.95
4-5    25.80
6+     40.20
Name: current_ctc_lpa, dtype: float64

/tmp/ipykernel_722/2629991593.py:14: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  exp_salary = backend.groupby('exp_band')['current_ctc_lpa'].median()

TASK 3.3

In [ ]:
sde = df[df['role_clean'].isin([
    'SDE Backend',
    'SDE Frontend',
    'SDE Full Stack'
])]

skills = ['AWS', 'ML', 'System Design', 'Kubernetes']

for skill in skills:

    with_skill = sde[sde['skills'].str.contains(skill, case=False, na=False)]

    without_skill = sde[~sde['skills'].str.contains(skill, case=False, na=False)]

    median_with = with_skill['current_ctc_lpa'].median()

    median_without = without_skill['current_ctc_lpa'].median()

    premium = ((median_with - median_without) / median_without) * 100

    print(f"{skill}")
    print(f"With Skill : {median_with:.2f} LPA")
    print(f"Without Skill : {median_without:.2f} LPA")
    print(f"Premium : {premium:.2f}%")
    print("-"*40)

AWS
With Skill : 20.95 LPA
Without Skill : 21.35 LPA
Premium : -1.87%
----------------------------------------
ML
With Skill : 20.65 LPA
Without Skill : 21.25 LPA
Premium : -2.82%
----------------------------------------
System Design
With Skill : 25.10 LPA
Without Skill : 20.90 LPA
Premium : 20.10%
----------------------------------------
Kubernetes
With Skill : 17.60 LPA
Without Skill : 21.40 LPA
Premium : -17.76%
----------------------------------------

TASK 3.4

In [ ]:
backend = df[df['role_clean'] == 'SDE Backend']

company_salary = backend.groupby('company_type_clean')['current_ctc_lpa'].median().sort_values(ascending=False)

print(company_salary.round(2))

if 'Unicorn' in company_salary.index and 'MNC' in company_salary.index:
    unicorn = company_salary['Unicorn']
    mnc = company_salary['MNC']

    premium = ((unicorn - mnc) / mnc) * 100

    print(f"\nUnicorn Premium over MNC = {premium:.2f}%")

company_type_clean
Unicorn        26.40
Mid-Size       20.70
Mnc            19.95
Early-Stage    17.15
Name: current_ctc_lpa, dtype: float64

TASK 3.5

In [ ]:
bins = [0,2,4,6,100]

labels = ['0-1','2-3','4-5','6+']

df['exp_band'] = pd.cut(df['years_exp'],
                        bins=bins,
                        labels=labels,
                        right=False)


group_size = df.groupby(
    ['role_clean','company_type_clean','exp_band']
)['current_ctc_lpa'].transform('count')


group_median = df.groupby(
    ['role_clean','company_type_clean','exp_band']
)['current_ctc_lpa'].transform('median')


df['group_size'] = group_size

df['group_median'] = group_median

df['gap'] = df['current_ctc_lpa'] - df['group_median']



underpaid = df[df['group_size'] >= 10]



top10 = underpaid.sort_values('gap').head(10)

print(top10[['employee_id',
             'role_clean',
             'company_type_clean',
             'years_exp',
             'current_ctc_lpa',
             'group_median',
             'gap']])

    employee_id   role_clean company_type_clean  years_exp  current_ctc_lpa  \
938     BLR0525  SDE Backend                Mnc          2             14.8
94      BLR0328  SDE Backend                Mnc          2             16.4
191     BLR0485  SDE Backend                Mnc          0              9.1
233     BLR0459  SDE Backend                Mnc          0              9.9
527     BLR0157  SDE Backend                Mnc          2             18.0
184     BLR0918  SDE Backend                Mnc          2             18.0
628     BLR0692  SDE Backend                Mnc          0             10.9
876     BLR0965  SDE Backend                Mnc          2             18.9
958     BLR0390  SDE Backend                Mnc          2             19.3
199     BLR0452  SDE Backend                Mnc          0             11.6

     group_median   gap
938         19.95 -5.15
94          19.95 -3.55
191         12.25 -3.15
233         12.25 -2.35
527         19.95 -1.95
184         19.95 -1.95
628         12.25 -1.35
876         19.95 -1.05
958         19.95 -0.65
199         12.25 -0.65

/tmp/ipykernel_722/2047895866.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['exp_band'] = pd.cut(df['years_exp'],
/tmp/ipykernel_722/2047895866.py:11: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  group_size = df.groupby(
/tmp/ipykernel_722/2047895866.py:16: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  group_median = df.groupby(

TASK 4

In [ ]:
print("="*65)
print("          BANGALORE TECH SALARY DECODER")
print("="*65)

print(f"Total Employees : {len(df)}")
print(f"Roles Analysed  : {df['role_clean'].nunique()}")
print()

print("="*65)
print("MEDIAN CTC BY ROLE")
print("="*65)

print(role_salary['Median_CTC'].round(2))

print()

print("="*65)
print("SDE BACKEND EXPERIENCE")
print("="*65)

print(exp_salary.round(2))

print()

print("="*65)
print("COMPANY TYPE MEDIAN")
print("="*65)

print(company_salary.round(2))

print()

print("="*65)
print("TOP 10 UNDERPAID PROFESSIONALS")
print("="*65)

print(top10[['employee_id',
             'role_clean',
             'company_type_clean',
             'gap']])

print("="*65)

=================================================================
          BANGALORE TECH SALARY DECODER
=================================================================
Total Employees : 1000
Roles Analysed  : 35

=================================================================
MEDIAN CTC BY ROLE
=================================================================
role_clean
Product Manager              31.60
Sr PM                        31.50
Product Lead                 31.10
PM                           30.10
ML Engineer                  27.50
Data Science Engineer        25.65
FE                           25.30
SDE FS                       24.60
Fullstack Dev                24.55
Frontend Developer           24.30
SRE                          24.25
Data Scientist               23.90
Infra Engineer               23.45
Site Reliability Engineer    22.20
UI/UX                        22.00
SDE Full Stack               21.70
Analytics Engineer           21.40
SDE Backend                  21.30
DevOps Engineer              21.15
SDE Frontend                 21.00
DS                           21.00
Business Systems Analyst     20.90
SDE-Backend                  20.60
BA                           20.50
UI Designer                  19.50
Product Designer             19.00
UX Designer                  18.00
Designer                     17.90
FullStack                    17.60
DevOps                       17.10
Data Analyst                 16.70
BI Analyst                   16.45
Business Analyst             16.40
SDE-Frontend                 16.25
DA                           15.90
Name: Median_CTC, dtype: float64

=================================================================
SDE BACKEND EXPERIENCE
=================================================================
exp_band
0-1    11.70
2-3    19.95
4-5    25.80
6+     40.20
Name: current_ctc_lpa, dtype: float64

=================================================================
COMPANY TYPE MEDIAN
=================================================================
company_type_clean
Unicorn        26.40
Mid-Size       20.70
Mnc            19.95
Early-Stage    17.15
Name: current_ctc_lpa, dtype: float64

=================================================================
TOP 10 UNDERPAID PROFESSIONALS
=================================================================
    employee_id   role_clean company_type_clean   gap
938     BLR0525  SDE Backend                Mnc -5.15
94      BLR0328  SDE Backend                Mnc -3.55
191     BLR0485  SDE Backend                Mnc -3.15
233     BLR0459  SDE Backend                Mnc -2.35
527     BLR0157  SDE Backend                Mnc -1.95
184     BLR0918  SDE Backend                Mnc -1.95
628     BLR0692  SDE Backend                Mnc -1.35
876     BLR0965  SDE Backend                Mnc -1.05
958     BLR0390  SDE Backend                Mnc -0.65
199     BLR0452  SDE Backend                Mnc -0.65
=================================================================

TASK 5

In [ ]:
# Standardize Role Names

role_map = {
    # Data Scientist
    'DS':'Data Scientist',
    'Data Scientist':'Data Scientist',
    'ML Engineer':'Data Scientist',
    'Data Science Engineer':'Data Scientist',

    # DevOps
    'DevOps':'DevOps Engineer',
    'DevOps Engineer':'DevOps Engineer',
    'Site Reliability Engineer':'DevOps Engineer',
    'SRE':'DevOps Engineer',
    'Infra Engineer':'DevOps Engineer',

    # Backend
    'SDE Backend':'SDE Backend',
    'Backend Dev':'SDE Backend',
    'Backend Developer':'SDE Backend',
    'Backend Engineer':'SDE Backend',
    'BE':'SDE Backend',
    'SDE-Backend':'SDE Backend',

    # Frontend
    'SDE Frontend':'SDE Frontend',
    'Frontend Dev':'SDE Frontend',
    'Frontend Engineer':'SDE Frontend',
    'Frontend Developer':'SDE Frontend',
    'FE':'SDE Frontend',
    'SDE-Frontend':'SDE Frontend',

    # Full Stack
    'SDE Full-Stack':'SDE Full Stack',
    'Full Stack Engineer':'SDE Full Stack',
    'FullStack':'SDE Full Stack',
    'Fullstack Dev':'SDE Full Stack',
    'SDE FS':'SDE Full Stack',

    # Product
    'Product Lead':'Product Manager',
    'Product Manager':'Product Manager',
    'PM':'Product Manager',
    'Sr PM':'Product Manager',

    # Data Analyst
    'DA':'Data Analyst',
    'Data Analyst':'Data Analyst',
    'BI Analyst':'Data Analyst',
    'Analytics Engineer':'Data Analyst',

    # Business Analyst
    'BA':'Business Analyst',
    'Business Analyst':'Business Analyst',
    'Business Systems Analyst':'Business Analyst',

    # UI/UX
    'UI/UX':'UI/UX Designer',
    'UI Designer':'UI/UX Designer',
    'UX Designer':'UI/UX Designer',
    'Designer':'UI/UX Designer',
    'Product Designer':'UI/UX Designer'
}

df['role_clean'] = df['Role '].map(role_map).fillna(df['Role '])

print(df['role_clean'].value_counts())

role_clean
Data Scientist      128
DevOps Engineer     127
SDE Backend         116
UI/UX Designer      116
Product Manager     113
Business Analyst    112
SDE Frontend        105
Data Analyst        101
SDE Full Stack       97
Name: count, dtype: int64

TASK 6

In [ ]:
print("="*60)
print("FINAL CHECKLIST")
print("="*60)

print("✓ Dataset Loaded")
print("✓ Data Cleaned")
print("✓ Role Standardized")
print("✓ Company Type Standardized")
print("✓ Education Tier Standardized")
print("✓ CTC Converted to LPA")
print("✓ Business Question 1 Completed")
print("✓ Business Question 2 Completed")
print("✓ Business Question 3 Completed")
print("✓ Business Question 4 Completed")
print("✓ Business Question 5 Completed")
print("✓ Final Salary Report Generated")
print("✓ Three Business Insights Added")

print("="*60)
print("PROJECT COMPLETED SUCCESSFULLY")
print("="*60)

============================================================
FINAL CHECKLIST
============================================================
✓ Dataset Loaded
✓ Data Cleaned
✓ Role Standardized
✓ Company Type Standardized
✓ Education Tier Standardized
✓ CTC Converted to LPA
✓ Business Question 1 Completed
✓ Business Question 2 Completed
✓ Business Question 3 Completed
✓ Business Question 4 Completed
✓ Business Question 5 Completed
✓ Final Salary Report Generated
✓ Three Business Insights Added
============================================================
PROJECT COMPLETED SUCCESSFULLY
============================================================